

I ) Créer une base de données que vous appelerez : CountriesDatas II ) Vous ajouterez deux tables à de cette nouvelle base:

[* les colonnes sont notées ci-dessous entre paranthèses]

​

    a) countries (code, name)

    b) populations (id, LOCATION, TIME , Value)

In [1]:
import pandas as pd
import mysql.connector
from mysql.connector import errorcode
import random
from datetime import datetime
from mysql.connector import Error
import time

mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="example",
    port="3307",
    database="CountriesDatas_II"
)
mycursor = mydb.cursor()

In [3]:
def creer_dict_pays():
    """
    lit fichier country.txt, enleve les caractères speciaux,creer un dictionnaire
    """
    try:
        
        dic_pays =	{

        }
       
        f_text = open("country.txt", "r") #ex : /dossier1/dossier2/mon_beau_fichier.txt
        #print(f_text)
        for ligne in f_text : 
            #print(ligne)
            ma_ligne_sans_caracteres  = ligne.replace('__****__', '')
            #print(ma_ligne_sans_caracteres)
            liste_par_ligne =ma_ligne_sans_caracteres.split()
            #print(liste_par_ligne)
            code = liste_par_ligne[0]
            name = liste_par_ligne[1]
            #print(name)
            #print(code)
            
            dic_pays[name] = code
            # dict_pays_new = pd.append(dict_pays[code], dict_pays[name])
        #print(dic_pays )
        return dic_pays    
    except Exception as e:
        print(e)

dict_pays = creer_dict_pays()
print(dict_pays)

{'Aruba': 'ABW', 'Afghanistan': 'AFG', 'Africa': 'AFRI', 'Angola': 'AGO', 'Anguilla': 'AIA', 'Albania': 'ALB', 'Andorra': 'AND', 'Netherlands': 'NLD', 'United': 'VIR', 'Argentina': 'ARG', 'Asia': 'ASIA', 'American': 'ASM', 'Antigua': 'ATG', 'Australia': 'AUS', 'Austria': 'AUT', 'Burundi': 'BDI', 'Belgium': 'BEL', 'Benin': 'BEN', 'Burkina': 'BFA', 'Bangladesh': 'BGD', 'Bulgaria': 'BGR', 'Bahrain': 'BHR', 'Bahamas': 'BHS', 'Belize': 'BLZ', 'Bermuda': 'BMU', 'Bolivia': 'BOL', 'Brazil': 'BRA', 'Barbados': 'BRB', 'Brunei': 'BRN', 'Bhutan': 'BTN', 'Botswana': 'BWA', 'Central': 'CAF', 'Canada': 'CAN', 'Cocos': 'CCK', 'Switzerland': 'CHE', 'Chile': 'CHL', 'China': 'CHN', 'Côte': 'CIV', 'Cameroon': 'CMR', 'Congo,': 'COD', 'Congo': 'COG', 'Cook': 'COK', 'Colombia': 'COL', 'Comoros': 'COM', 'Cape': 'CPV', 'Costa': 'CRI', 'Former': 'USSR', 'Czech': 'CSFR-CZE', 'Slovak': 'CSFR-SVK', 'Cuba': 'CUB', 'Cayman': 'CYM', 'Cyprus': 'CYP', 'Germany': 'DEU', 'Djibouti': 'DJI', 'Dominica': 'DMA', 'Denmark': 'DNK', 'Dominican': 'DOM', 'Algeria': 'DZA', 'Ecuador': 'ECU', 'Egypt': 'EGY', 'Eritrea': 'ERI', 'Western': 'ESH', 'Spain': 'ESP', 'Ethiopia': 'ETH', 'Europe': 'EURO', 'Finland': 'FIN', 'Fiji': 'FJI', 'Falkland': 'FLK', 'France': 'FRA', 'Micronesia,': 'FSM', 'Bosnia-Herzegovina': 'FYUG-BIH', 'Croatia': 'FYUG-HRV', 'Macedonia': 'FYUG-MKD', 'Slovenia': 'FYUG-SVN', 'Serbia': 'FYUG-YUG', 'Gabon': 'GAB', 'Ghana': 'GHA', 'Gibraltar': 'GIB', 'Guinea': 'GIN', 'Gambia': 'GMB', 'Guinea-Bissau': 'GNB', 'Equatorial': 'GNQ', 'Greece': 'GRC', 'Grenada': 'GRD', 'Guatemala': 'GTM', 'Guam': 'GUM', 'Guyana': 'GUY', 'Hong': 'HKG', 'Honduras': 'HND', 'Haiti': 'HTI', 'Hungary': 'HUN', 'Indonesia': 'IDN', 'India': 'IND', 'British': 'VGB', 'Ireland': 'IRL', 'Iran': 'IRN', 'Iraq': 'IRQ', 'Iceland': 'ISL', 'Israel': 'ISR', 'Italy': 'ITA', 'Jamaica': 'JAM', 'Jordan': 'JOR', 'Japan': 'JPN', 'Kenya': 'KEN', 'Cambodia': 'KHM', 'Kiribati': 'KIR', 'Saint': 'VCT', 'North': 'NOAM', 'South': 'ZAF', 'Kuwait': 'KWT', 'Laos': 'LAO', 'Lebanon': 'LBN', 'Liberia': 'LBR', 'Libya': 'LBY', 'Liechtenstein': 'LIE', 'Sri': 'LKA', 'Lesotho': 'LSO', 'Luxembourg': 'LUX', 'Macau': 'MAC', 'Morocco': 'MAR', 'Monaco': 'MCO', 'Madagascar': 'MDG', 'Maldives': 'MDV', 'Mexico': 'MEX', 'Marshall': 'MHL', 'Mali': 'MLI', 'Malta': 'MLT', 'Myanmar': 'MMR', 'Mongolia': 'MNG', 'Northern': 'MNP', 'Mozambique': 'MOZ', 'Mauritania': 'MRT', 'Montserrat': 'MSR', 'Mauritius': 'MUS', 'Malawi': 'MWI', 'Malaysia': 'MYS', 'Namibia': 'NAM', 'Niger': 'NER', 'Norfolk': 'NFK', 'Nigeria': 'NGA', 'Nicaragua': 'NIC', 'Niue': 'NIU', 'Norway': 'NOR', 'Nepal': 'NPL', 'Nauru': 'NRU', 'New': 'NZL', 'Oceania': 'OCEA', 'Oman': 'OMN', 'Other': 'OTH', 'Pakistan': 'PAK', 'Panama': 'PAN', 'Pitcairn': 'PCN', 'Peru': 'PER', 'Philippines': 'PHL', 'Pacific': 'PLW', 'Papua': 'PNG', 'Poland': 'POL', 'Puerto': 'PRI', 'Portugal': 'PRT', 'Paraguay': 'PRY', 'Occupied': 'PSE', 'Qatar': 'QAT', 'Romania': 'ROU', 'Rwanda': 'RWA', 'Saudi': 'SAU', 'Sudan': 'SDN', 'Senegal': 'SEN', 'Singapore': 'SGP', 'Svalbard': 'SJM', 'Solomon': 'SLB', 'Sierra': 'SLE', 'El': 'SLV', 'San': 'SMR', 'Somalia': 'SOM', 'Sao': 'STP', 'Suriname': 'SUR', 'Sweden': 'SWE', 'Swaziland': 'SWZ', 'Seychelles': 'SYC', 'Syria': 'SYR', 'Turks': 'TCA', 'Chad': 'TCD', 'Togo': 'TGO', 'Thailand': 'THA', 'Tokelau': 'TKL', 'Timor-Leste': 'TLS', 'East': 'TMP', 'Tonga': 'TON', 'Trinidad': 'TTO', 'Tunisia': 'TUN', 'Turkey': 'TUR', 'Tuvalu': 'TUV', 'Chinese': 'TWN', 'Uruguay': 'URY', 'Armenia': 'USSR-ARM', 'Azerbaidjan': 'USSR-AZE', 'Belarus': 'USSR-BLR', 'Estonia': 'USSR-EST', 'Georgia': 'USSR-GEO', 'Kazakhstan': 'USSR-KAZ', 'Kirghizistan': 'USSR-KGZ', 'Lithuania': 'USSR-LTU', 'Latvia': 'USSR-LVA', 'Moldova': 'USSR-MDA', 'Russia': 'USSR-RUS', 'Tadjikistan': 'USSR-TJK', 'Turkménistan': 'USSR-TKM', 'Ukraine': 'USSR-UKR', 'Uzbekistan': 'USSR-UZB', 'Holy': 'VAT', 'Venezuela': 'VEN', 'Vietnam': 'VNM', 'Vanuatu': 'VUT', 'Samoa': 'WSM', 'Yemen': 'YEM', 'Zambia': 'ZMB', 'Zimbabwe': 'ZWE'}

In [4]:
list_of_countries = list(dict_pays.items())
print(list_of_countries)

[('Aruba', 'ABW'), ('Afghanistan', 'AFG'), ('Africa', 'AFRI'), ('Angola', 'AGO'), ('Anguilla', 'AIA'), ('Albania', 'ALB'), ('Andorra', 'AND'), ('Netherlands', 'NLD'), ('United', 'VIR'), ('Argentina', 'ARG'), ('Asia', 'ASIA'), ('American', 'ASM'), ('Antigua', 'ATG'), ('Australia', 'AUS'), ('Austria', 'AUT'), ('Burundi', 'BDI'), ('Belgium', 'BEL'), ('Benin', 'BEN'), ('Burkina', 'BFA'), ('Bangladesh', 'BGD'), ('Bulgaria', 'BGR'), ('Bahrain', 'BHR'), ('Bahamas', 'BHS'), ('Belize', 'BLZ'), ('Bermuda', 'BMU'), ('Bolivia', 'BOL'), ('Brazil', 'BRA'), ('Barbados', 'BRB'), ('Brunei', 'BRN'), ('Bhutan', 'BTN'), ('Botswana', 'BWA'), ('Central', 'CAF'), ('Canada', 'CAN'), ('Cocos', 'CCK'), ('Switzerland', 'CHE'), ('Chile', 'CHL'), ('China', 'CHN'), ('Côte', 'CIV'), ('Cameroon', 'CMR'), ('Congo,', 'COD'), ('Congo', 'COG'), ('Cook', 'COK'), ('Colombia', 'COL'), ('Comoros', 'COM'), ('Cape', 'CPV'), ('Costa', 'CRI'), ('Former', 'USSR'), ('Czech', 'CSFR-CZE'), ('Slovak', 'CSFR-SVK'), ('Cuba', 'CUB'), ('Cayman', 'CYM'), ('Cyprus', 'CYP'), ('Germany', 'DEU'), ('Djibouti', 'DJI'), ('Dominica', 'DMA'), ('Denmark', 'DNK'), ('Dominican', 'DOM'), ('Algeria', 'DZA'), ('Ecuador', 'ECU'), ('Egypt', 'EGY'), ('Eritrea', 'ERI'), ('Western', 'ESH'), ('Spain', 'ESP'), ('Ethiopia', 'ETH'), ('Europe', 'EURO'), ('Finland', 'FIN'), ('Fiji', 'FJI'), ('Falkland', 'FLK'), ('France', 'FRA'), ('Micronesia,', 'FSM'), ('Bosnia-Herzegovina', 'FYUG-BIH'), ('Croatia', 'FYUG-HRV'), ('Macedonia', 'FYUG-MKD'), ('Slovenia', 'FYUG-SVN'), ('Serbia', 'FYUG-YUG'), ('Gabon', 'GAB'), ('Ghana', 'GHA'), ('Gibraltar', 'GIB'), ('Guinea', 'GIN'), ('Gambia', 'GMB'), ('Guinea-Bissau', 'GNB'), ('Equatorial', 'GNQ'), ('Greece', 'GRC'), ('Grenada', 'GRD'), ('Guatemala', 'GTM'), ('Guam', 'GUM'), ('Guyana', 'GUY'), ('Hong', 'HKG'), ('Honduras', 'HND'), ('Haiti', 'HTI'), ('Hungary', 'HUN'), ('Indonesia', 'IDN'), ('India', 'IND'), ('British', 'VGB'), ('Ireland', 'IRL'), ('Iran', 'IRN'), ('Iraq', 'IRQ'), ('Iceland', 'ISL'), ('Israel', 'ISR'), ('Italy', 'ITA'), ('Jamaica', 'JAM'), ('Jordan', 'JOR'), ('Japan', 'JPN'), ('Kenya', 'KEN'), ('Cambodia', 'KHM'), ('Kiribati', 'KIR'), ('Saint', 'VCT'), ('North', 'NOAM'), ('South', 'ZAF'), ('Kuwait', 'KWT'), ('Laos', 'LAO'), ('Lebanon', 'LBN'), ('Liberia', 'LBR'), ('Libya', 'LBY'), ('Liechtenstein', 'LIE'), ('Sri', 'LKA'), ('Lesotho', 'LSO'), ('Luxembourg', 'LUX'), ('Macau', 'MAC'), ('Morocco', 'MAR'), ('Monaco', 'MCO'), ('Madagascar', 'MDG'), ('Maldives', 'MDV'), ('Mexico', 'MEX'), ('Marshall', 'MHL'), ('Mali', 'MLI'), ('Malta', 'MLT'), ('Myanmar', 'MMR'), ('Mongolia', 'MNG'), ('Northern', 'MNP'), ('Mozambique', 'MOZ'), ('Mauritania', 'MRT'), ('Montserrat', 'MSR'), ('Mauritius', 'MUS'), ('Malawi', 'MWI'), ('Malaysia', 'MYS'), ('Namibia', 'NAM'), ('Niger', 'NER'), ('Norfolk', 'NFK'), ('Nigeria', 'NGA'), ('Nicaragua', 'NIC'), ('Niue', 'NIU'), ('Norway', 'NOR'), ('Nepal', 'NPL'), ('Nauru', 'NRU'), ('New', 'NZL'), ('Oceania', 'OCEA'), ('Oman', 'OMN'), ('Other', 'OTH'), ('Pakistan', 'PAK'), ('Panama', 'PAN'), ('Pitcairn', 'PCN'), ('Peru', 'PER'), ('Philippines', 'PHL'), ('Pacific', 'PLW'), ('Papua', 'PNG'), ('Poland', 'POL'), ('Puerto', 'PRI'), ('Portugal', 'PRT'), ('Paraguay', 'PRY'), ('Occupied', 'PSE'), ('Qatar', 'QAT'), ('Romania', 'ROU'), ('Rwanda', 'RWA'), ('Saudi', 'SAU'), ('Sudan', 'SDN'), ('Senegal', 'SEN'), ('Singapore', 'SGP'), ('Svalbard', 'SJM'), ('Solomon', 'SLB'), ('Sierra', 'SLE'), ('El', 'SLV'), ('San', 'SMR'), ('Somalia', 'SOM'), ('Sao', 'STP'), ('Suriname', 'SUR'), ('Sweden', 'SWE'), ('Swaziland', 'SWZ'), ('Seychelles', 'SYC'), ('Syria', 'SYR'), ('Turks', 'TCA'), ('Chad', 'TCD'), ('Togo', 'TGO'), ('Thailand', 'THA'), ('Tokelau', 'TKL'), ('Timor-Leste', 'TLS'), ('East', 'TMP'), ('Tonga', 'TON'), ('Trinidad', 'TTO'), ('Tunisia', 'TUN'), ('Turkey', 'TUR'), ('Tuvalu', 'TUV'), ('Chinese', 'TWN'), ('Uruguay', 'URY'), ('Armenia', 'USSR-ARM'), ('Azerbaidjan', 'USSR-AZE'), ('Belarus', 'USSR-BLR'), ('Estonia', 'USSR-EST'), ('Georgia', 'USSR-GEO'), ('Kazakhstan', 'USSR-KAZ'), ('Kirghizistan', 'USSR-KGZ'), ('Lithuania', 'USSR-LTU'), ('Latvia', 'USSR-LVA'), ('Moldova', 'USSR-MDA'), ('Russia', 'USSR-RUS'), ('Tadjikistan', 'USSR-TJK'), ('Turkménistan', 'USSR-TKM'), ('Ukraine', 'USSR-UKR'), ('Uzbekistan', 'USSR-UZB'), ('Holy', 'VAT'), ('Venezuela', 'VEN'), ('Vietnam', 'VNM'), ('Vanuatu', 'VUT'), ('Samoa', 'WSM'), ('Yemen', 'YEM'), ('Zambia', 'ZMB'), ('Zimbabwe', 'ZWE')]

In [5]:
list_of_country = [{'code':'ABW', 'name':'Aruba'}, {'code':'AFG', 'name':'Afghanistan'}, {'code':'AFRI', 'name':'Africa'}, {'code':'AGO', 'name':'Angola'}, {'code':'AIA', 'name':'Anguilla'}, {'code':'ALB', 'name':'Albania'}, {'code':'AND', 'name':'Andorra'}, {'code':'ANT', 'name':'Netherlands'}, {'code':'ARE', 'name':'United'}, {'code':'ARG', 'name':'Argentina'}, {'code':'ASIA', 'name':'Asia'}, {'code':'ASM', 'name':'American'}, {'code':'ATG', 'name':'Antigua'}, {'code':'AUS', 'name':'Australia'}, {'code':'AUT', 'name':'Austria'}, {'code':'BDI', 'name':'Burundi'}, {'code':'BEL', 'name':'Belgium'}, {'code':'BEN', 'name':'Benin'}, {'code':'BFA', 'name':'Burkina'}, {'code':'BGD', 'name':'Bangladesh'}, {'code':'BGR', 'name':'Bulgaria'}, {'code':'BHR', 'name':'Bahrain'}, {'code':'BHS', 'name':'Bahamas'}, {'code':'BLZ', 'name':'Belize'}, {'code':'BMU', 'name':'Bermuda'}, {'code':'BOL', 'name':'Bolivia'}, {'code':'BRA', 'name':'Brazil'}, {'code':'BRB', 'name':'Barbados'}, {'code':'BRN', 'name':'Brunei'}, {'code':'BTN', 'name':'Bhutan'}, {'code':'BWA', 'name':'Botswana'}, {'code':'CAF', 'name':'Central'}, {'code':'CAN', 'name':'Canada'}, {'code':'CCK', 'name':'Cocos'}, {'code':'CHE', 'name':'Switzerland'}, {'code':'CHL', 'name':'Chile'}, {'code':'CHN', 'name':'China'}, {'code':'CIV', 'name':'Côte'}, {'code':'CMR', 'name':'Cameroon'}, {'code':'COD', 'name':'Congo'}, {'code':'COG', 'name':'Congo'}, {'code':'COK', 'name':'Cook'}, {'code':'COL', 'name':'Colombia'}, {'code':'COM', 'name':'Comoros'}, {'code':'CPV', 'name':'Cape'}, {'code':'CRI', 'name':'Costa'}, {'code':'CSFR', 'name':'Former'}, {'code':'CSFR-CZE', 'name':'Czech'}, {'code':'CSFR-SVK', 'name':'Slovak'},{'code':'CUB', 'name':'Cuba'}, {'code':'CYM', 'name':'Cayman'}, {'code':'CYP', 'name':'Cyprus'}, {'code':'DEU', 'name':'Germany'}, {'code':'DJI', 'name':'Djibouti'}, {'code':'DMA', 'name':'Dominica'}, {'code':'DNK', 'name':'Denmark'}, {'code':'DOM', 'name':'Dominican'}, {'code':'DZA', 'name':'Algeria'}, {'code':'ECU', 'name':'Ecuador'}, {'code':'EGY', 'name':'Egypt'}, {'code':'ERI', 'name':'Eritrea'}, {'code':'ESH', 'name':'Western'}, {'code':'ESP', 'name':'Spain'}, {'code':'ETH', 'name':'Ethiopia'}, {'code':'EURO', 'name':'Europe'}, {'code':'FIN','name': 'Finland'}, {'code':'FJI', 'name':'Fiji'}, {'code':'FLK', 'name':'Falkland'}, {'code':'FRA', 'name':'France'}, {'code':'FSM', 'name':'Micronesia'}, {'code':'FYUG', 'name':'Former'}, {'code':'FYUG-BIH', 'name':'Bosnia-Herzegovina'}, {'code':'FYUG-HRV', 'name':'Croatia'}, {'code':'FYUG-MKD', 'name':'Macedonia'}, {'code':'FYUG-SVN', 'name':'Slovenia'}, {'code':'FYUG-YUG', 'name':'Serbia'}, {'code':'GAB', 'name':'Gabon'}, {'code':'GBR', 'name':'United'}, {'code':'GHA', 'name':'Ghana'}, {'code':'GIB', 'name':'Gibraltar'}, {'code':'GIN', 'name':'Guinea'}, {'code':'GMB', 'name':'Gambia'}, {'code':'GNB', 'name':'Guinea-Bissau'}, {'code':'GNQ', 'name':'Equatorial'}, {'code':'GRC', 'name':'Greece'}, {'code':'GRD', 'name':'Grenada'}, {'code':'GTM', 'name':'Guatemala'}, {'code':'GUM', 'name':'Guam'}, {'code':'GUY', 'name':'Guyana'}, {'code':'HKG', 'name':'Hong'}, {'code':'HND', 'name':'Honduras'}, {'code':'HTI', 'name':'Haiti'}, {'code':'HUN', 'name':'Hungary'}, {'code':'IDN', 'name':'Indonesia'}, {'code':'IND', 'name':'India'}, {'code':'IOT','name': 'British'}, {'code':'IRL', 'name':'Ireland'}, {'code':'IRN', 'name':'Iran'}, {'code':'IRQ', 'name':'Iraq'}, {'code':'ISL', 'name':'Iceland'}, {'code':'ISR','name': 'Israel'}, {'code':'ITA', 'name':'Italy'}, {'code':'JAM', 'name':'Jamaica'}, {'code':'JOR', 'name':'Jordan'}, {'code':'JPN','name': 'Japan'}, {'code':'KEN', 'name':'Kenya'}, {'code':'KHM', 'name':'Cambodia'}, {'code':'KIR', 'name':'Kiribati'}, {'code':'KNA', 'name':'Saint'}, {'code':'KOREA-NO', 'name':'North'}, {'code':'KOREA-NS', 'name':'South'}, {'code':'KOREA-SO', 'name':'North'}, {'code':'KWT', 'name':'Kuwait'}, {'code':'LAO', 'name':'Laos'}, {'code':'LBN', 'name':'Lebanon'}, {'code':'LBR', 'name':'Liberia'}, {'code':'LBY', 'name':'Libya'}, {'code':'LCA', 'name':'Saint'}, {'code':'LIE', 'name':'Liechtenstein'}, {'code':'LKA', 'name':'Sri'}, {'code':'LSO', 'name':'Lesotho'}, {'code':'LUX', 'name':'Luxembourg'}, {'code':'MAC', 'name':'Macau'}, {'code':'MAR', 'name':'Morocco'}, {'code':'MCO', 'name':'Monaco'}, {'code':'MDG', 'name':'Madagascar'}, {'code':'MDV', 'name':'Maldives'}, {'code':'MEX','name': 'Mexico'}, {'code':'MHL','name':'Marshall'}, {'code':'MLI', 'name':'Mali'}, {'code':'MLT', 'name':'Malta'}, {'code':'MMR', 'name':'Myanmar'}, {'code':'MNG', 'name':'Mongolia'}, {'code':'MNP', 'name':'Northern'}, {'code':'MOZ', 'name':'Mozambique'}, {'code':'MRT', 'name':'Mauritania'}, {'code':'MSR', 'name':'Montserrat'}, {'code':'MUS', 'name':'Mauritius'}, {'code':'MWI', 'name':'Malawi'}, {'code':'MYS', 'name':'Malaysia'}, {'code':'NAM', 'name':'Namibia'}, {'code':'NER', 'name':'Niger'}, {'code':'NFK', 'name':'Norfolk'}, {'code':'NGA', 'name':'Nigeria'}, {'code':'NIC', 'name':'Nicaragua'}, {'code':'NIU', 'name':'Niue'}, {'code':'NLD', 'name':'Netherlands'}, {'code':'NOAM', 'name':'North'}, {'code':'NOR', 'name':'Norway'}, {'code':'NPL', 'name':'Nepal'}, {'code':'NRU', 'name':'Nauru'}, {'code':'NZL', 'name':'New'}, {'code':'OCEA', 'name':'Oceania'}, {'code':'OMN', 'name':'Oman'}, {'code':'OTH', 'name':'Other'}, {'code':'PAK', 'name':'Pakistan'}, {'code':'PAN', 'name':'Panama'}, {'code':'PCN', 'name':'Pitcairn'}, {'code':'PER', 'name':'Peru'}, {'code':'PHL','name':'Philippines'}, {'code':'PLW', 'name':'Pacific'}, {'code':'PNG', 'name':'Papua'}, {'code':'POL', 'name':'Poland'}, {'code':'PRI', 'name':'Puerto'}, {'code':'PRT', 'name':'Portugal'}, {'code':'PRY', 'name':'Paraguay'}, {'code':'PSE', 'name':'Occupied'}, {'code':'QAT', 'name':'Qatar'}, {'code':'ROU', 'name':'Romania'}, {'code':'RWA', 'name':'Rwanda'}, {'code':'SAU', 'name':'Saudi'}, {'code':'SCAC', 'name':'South'}, {'code':'SDN', 'name':'Sudan'}, {'code':'SEN', 'name':'Senegal'}, {'code':'SGP', 'name':'Singapore'}, {'code':'SHN', 'name':'Saint'}, {'code':'SJM', 'name':'Svalbard'}, {'code':'SLB', 'name':'Solomon'}, {'code':'SLE', 'name':'Sierra'}, {'code':'SLV', 'name':'El'}, {'code':'SMR', 'name':'San'}, {'code':'SOM', 'name':'Somalia'}, {'code':'STP', 'name':'Sao'}, {'code':'SUR', 'name':'Suriname'}, {'code':'SWE', 'name':'Sweden'}, {'code':'SWZ', 'name':'Swaziland'}, {'code':'SYC','name': 'Seychelles'}, {'code':'SYR','name': 'Syria'}, {'code':'TCA','name': 'Turks'}, {'code':'TCD', 'name':'Chad'}, {'code':'TGO', 'name':'Togo'}, {'code':'THA', 'name':'Thailand'}, {'code':'TKL', 'name':'Tokelau'}, {'code':'TLS', 'name':'Timor-Leste'}, {'code':'TMP', 'name':'East'}, {'code':'TON', 'name':'Tonga'}, {'code':'TTO', 'name':'Trinidad'}, {'code':'TUN', 'name':'Tunisia'}, {'code':'TUR', 'name':'Turkey'}, {'code':'TUV', 'name':'Tuvalu'}, {'code':'TWN', 'name':'Chinese'}, {'code':'TZA', 'name':'United'}, {'code':'URY', 'name':'Uruguay'}, {'code':'USA', 'name':'United'}, {'code':'USSR', 'name':'Former'}, {'code':'USSR-ARM', 'name':'Armenia'}, {'code':'USSR-AZE', 'name':'Azerbaidjan'}, {'code':'USSR-BLR', 'name':'Belarus'}, {'code':'USSR-EST', 'name':'Estonia'}, {'code':'USSR-GEO','name': 'Georgia'}, {'code':'USSR-KAZ', 'name':'Kazakhstan'}, {'code':'USSR-KGZ', 'name':'Kirghizistan'}, {'code':'USSR-LTU','name': 'Lithuania'}, {'code':'USSR-LVA', 'name':'Latvia'}, {'code':'USSR-MDA', 'name':'Moldova'}, {'code':'USSR-RUS','name': 'Russia'}, {'code':'USSR-TJK', 'name':'Tadjikistan'}, {'code':'USSR-TKM','name': 'Turkménistan'}, {'code':'USSR-UKR', 'name':'Ukraine'}, {'code':'USSR-UZB','name': 'Uzbekistan'}, {'code':'VAT','name': 'Holy'}, {'code':'VCT', 'name':'Saint'}, {'code':'VEN', 'name':'Venezuela'}, {'code':'VGB', 'name':'British'}, {'code':'VIR','name':'United'}, {'code':'VNM', 'name':'Vietnam'}, {'code':'VUT', 'name':'Vanuatu'}, {'code':'WSM', 'name':'Samoa'}, {'code':'YEM','name':'Yemen'}, {'code':'ZAF', 'name':'South'}, {'code':'ZMB', 'name':'Zambia'}, {'code':'ZWE','name': 'Zimbabwe'}]
print(list_of_country)

[{'code': 'ABW', 'name': 'Aruba'}, {'code': 'AFG', 'name': 'Afghanistan'}, {'code': 'AFRI', 'name': 'Africa'}, {'code': 'AGO', 'name': 'Angola'}, {'code': 'AIA', 'name': 'Anguilla'}, {'code': 'ALB', 'name': 'Albania'}, {'code': 'AND', 'name': 'Andorra'}, {'code': 'ANT', 'name': 'Netherlands'}, {'code': 'ARE', 'name': 'United'}, {'code': 'ARG', 'name': 'Argentina'}, {'code': 'ASIA', 'name': 'Asia'}, {'code': 'ASM', 'name': 'American'}, {'code': 'ATG', 'name': 'Antigua'}, {'code': 'AUS', 'name': 'Australia'}, {'code': 'AUT', 'name': 'Austria'}, {'code': 'BDI', 'name': 'Burundi'}, {'code': 'BEL', 'name': 'Belgium'}, {'code': 'BEN', 'name': 'Benin'}, {'code': 'BFA', 'name': 'Burkina'}, {'code': 'BGD', 'name': 'Bangladesh'}, {'code': 'BGR', 'name': 'Bulgaria'}, {'code': 'BHR', 'name': 'Bahrain'}, {'code': 'BHS', 'name': 'Bahamas'}, {'code': 'BLZ', 'name': 'Belize'}, {'code': 'BMU', 'name': 'Bermuda'}, {'code': 'BOL', 'name': 'Bolivia'}, {'code': 'BRA', 'name': 'Brazil'}, {'code': 'BRB', 'name': 'Barbados'}, {'code': 'BRN', 'name': 'Brunei'}, {'code': 'BTN', 'name': 'Bhutan'}, {'code': 'BWA', 'name': 'Botswana'}, {'code': 'CAF', 'name': 'Central'}, {'code': 'CAN', 'name': 'Canada'}, {'code': 'CCK', 'name': 'Cocos'}, {'code': 'CHE', 'name': 'Switzerland'}, {'code': 'CHL', 'name': 'Chile'}, {'code': 'CHN', 'name': 'China'}, {'code': 'CIV', 'name': 'Côte'}, {'code': 'CMR', 'name': 'Cameroon'}, {'code': 'COD', 'name': 'Congo'}, {'code': 'COG', 'name': 'Congo'}, {'code': 'COK', 'name': 'Cook'}, {'code': 'COL', 'name': 'Colombia'}, {'code': 'COM', 'name': 'Comoros'}, {'code': 'CPV', 'name': 'Cape'}, {'code': 'CRI', 'name': 'Costa'}, {'code': 'CSFR', 'name': 'Former'}, {'code': 'CSFR-CZE', 'name': 'Czech'}, {'code': 'CSFR-SVK', 'name': 'Slovak'}, {'code': 'CUB', 'name': 'Cuba'}, {'code': 'CYM', 'name': 'Cayman'}, {'code': 'CYP', 'name': 'Cyprus'}, {'code': 'DEU', 'name': 'Germany'}, {'code': 'DJI', 'name': 'Djibouti'}, {'code': 'DMA', 'name': 'Dominica'}, {'code': 'DNK', 'name': 'Denmark'}, {'code': 'DOM', 'name': 'Dominican'}, {'code': 'DZA', 'name': 'Algeria'}, {'code': 'ECU', 'name': 'Ecuador'}, {'code': 'EGY', 'name': 'Egypt'}, {'code': 'ERI', 'name': 'Eritrea'}, {'code': 'ESH', 'name': 'Western'}, {'code': 'ESP', 'name': 'Spain'}, {'code': 'ETH', 'name': 'Ethiopia'}, {'code': 'EURO', 'name': 'Europe'}, {'code': 'FIN', 'name': 'Finland'}, {'code': 'FJI', 'name': 'Fiji'}, {'code': 'FLK', 'name': 'Falkland'}, {'code': 'FRA', 'name': 'France'}, {'code': 'FSM', 'name': 'Micronesia'}, {'code': 'FYUG', 'name': 'Former'}, {'code': 'FYUG-BIH', 'name': 'Bosnia-Herzegovina'}, {'code': 'FYUG-HRV', 'name': 'Croatia'}, {'code': 'FYUG-MKD', 'name': 'Macedonia'}, {'code': 'FYUG-SVN', 'name': 'Slovenia'}, {'code': 'FYUG-YUG', 'name': 'Serbia'}, {'code': 'GAB', 'name': 'Gabon'}, {'code': 'GBR', 'name': 'United'}, {'code': 'GHA', 'name': 'Ghana'}, {'code': 'GIB', 'name': 'Gibraltar'}, {'code': 'GIN', 'name': 'Guinea'}, {'code': 'GMB', 'name': 'Gambia'}, {'code': 'GNB', 'name': 'Guinea-Bissau'}, {'code': 'GNQ', 'name': 'Equatorial'}, {'code': 'GRC', 'name': 'Greece'}, {'code': 'GRD', 'name': 'Grenada'}, {'code': 'GTM', 'name': 'Guatemala'}, {'code': 'GUM', 'name': 'Guam'}, {'code': 'GUY', 'name': 'Guyana'}, {'code': 'HKG', 'name': 'Hong'}, {'code': 'HND', 'name': 'Honduras'}, {'code': 'HTI', 'name': 'Haiti'}, {'code': 'HUN', 'name': 'Hungary'}, {'code': 'IDN', 'name': 'Indonesia'}, {'code': 'IND', 'name': 'India'}, {'code': 'IOT', 'name': 'British'}, {'code': 'IRL', 'name': 'Ireland'}, {'code': 'IRN', 'name': 'Iran'}, {'code': 'IRQ', 'name': 'Iraq'}, {'code': 'ISL', 'name': 'Iceland'}, {'code': 'ISR', 'name': 'Israel'}, {'code': 'ITA', 'name': 'Italy'}, {'code': 'JAM', 'name': 'Jamaica'}, {'code': 'JOR', 'name': 'Jordan'}, {'code': 'JPN', 'name': 'Japan'}, {'code': 'KEN', 'name': 'Kenya'}, {'code': 'KHM', 'name': 'Cambodia'}, {'code': 'KIR', 'name': 'Kiribati'}, {'code': 'KNA', 'name': 'Saint'}, {'code': 'KOREA-NO', 'name': 'North'}, {'code': 'KOREA-NS', 'name': 'South'}, {'code': 'KOREA-SO', 'name': 'North'}, {'code': 'KWT', 'name': 'Kuwait'}, {'code': 'LAO', 'name': 'Laos'}, {'code': 'LBN', 'name': 'Lebanon'}, {'code': 'LBR', 'name': 'Liberia'}, {'code': 'LBY', 'name': 'Libya'}, {'code': 'LCA', 'name': 'Saint'}, {'code': 'LIE', 'name': 'Liechtenstein'}, {'code': 'LKA', 'name': 'Sri'}, {'code': 'LSO', 'name': 'Lesotho'}, {'code': 'LUX', 'name': 'Luxembourg'}, {'code': 'MAC', 'name': 'Macau'}, {'code': 'MAR', 'name': 'Morocco'}, {'code': 'MCO', 'name': 'Monaco'}, {'code': 'MDG', 'name': 'Madagascar'}, {'code': 'MDV', 'name': 'Maldives'}, {'code': 'MEX', 'name': 'Mexico'}, {'code': 'MHL', 'name': 'Marshall'}, {'code': 'MLI', 'name': 'Mali'}, {'code': 'MLT', 'name': 'Malta'}, {'code': 'MMR', 'name': 'Myanmar'}, {'code': 'MNG', 'name': 'Mongolia'}, {'code': 'MNP', 'name': 'Northern'}, {'code': 'MOZ', 'name': 'Mozambique'}, {'code': 'MRT', 'name': 'Mauritania'}, {'code': 'MSR', 'name': 'Montserrat'}, {'code': 'MUS', 'name': 'Mauritius'}, {'code': 'MWI', 'name': 'Malawi'}, {'code': 'MYS', 'name': 'Malaysia'}, {'code': 'NAM', 'name': 'Namibia'}, {'code': 'NER', 'name': 'Niger'}, {'code': 'NFK', 'name': 'Norfolk'}, {'code': 'NGA', 'name': 'Nigeria'}, {'code': 'NIC', 'name': 'Nicaragua'}, {'code': 'NIU', 'name': 'Niue'}, {'code': 'NLD', 'name': 'Netherlands'}, {'code': 'NOAM', 'name': 'North'}, {'code': 'NOR', 'name': 'Norway'}, {'code': 'NPL', 'name': 'Nepal'}, {'code': 'NRU', 'name': 'Nauru'}, {'code': 'NZL', 'name': 'New'}, {'code': 'OCEA', 'name': 'Oceania'}, {'code': 'OMN', 'name': 'Oman'}, {'code': 'OTH', 'name': 'Other'}, {'code': 'PAK', 'name': 'Pakistan'}, {'code': 'PAN', 'name': 'Panama'}, {'code': 'PCN', 'name': 'Pitcairn'}, {'code': 'PER', 'name': 'Peru'}, {'code': 'PHL', 'name': 'Philippines'}, {'code': 'PLW', 'name': 'Pacific'}, {'code': 'PNG', 'name': 'Papua'}, {'code': 'POL', 'name': 'Poland'}, {'code': 'PRI', 'name': 'Puerto'}, {'code': 'PRT', 'name': 'Portugal'}, {'code': 'PRY', 'name': 'Paraguay'}, {'code': 'PSE', 'name': 'Occupied'}, {'code': 'QAT', 'name': 'Qatar'}, {'code': 'ROU', 'name': 'Romania'}, {'code': 'RWA', 'name': 'Rwanda'}, {'code': 'SAU', 'name': 'Saudi'}, {'code': 'SCAC', 'name': 'South'}, {'code': 'SDN', 'name': 'Sudan'}, {'code': 'SEN', 'name': 'Senegal'}, {'code': 'SGP', 'name': 'Singapore'}, {'code': 'SHN', 'name': 'Saint'}, {'code': 'SJM', 'name': 'Svalbard'}, {'code': 'SLB', 'name': 'Solomon'}, {'code': 'SLE', 'name': 'Sierra'}, {'code': 'SLV', 'name': 'El'}, {'code': 'SMR', 'name': 'San'}, {'code': 'SOM', 'name': 'Somalia'}, {'code': 'STP', 'name': 'Sao'}, {'code': 'SUR', 'name': 'Suriname'}, {'code': 'SWE', 'name': 'Sweden'}, {'code': 'SWZ', 'name': 'Swaziland'}, {'code': 'SYC', 'name': 'Seychelles'}, {'code': 'SYR', 'name': 'Syria'}, {'code': 'TCA', 'name': 'Turks'}, {'code': 'TCD', 'name': 'Chad'}, {'code': 'TGO', 'name': 'Togo'}, {'code': 'THA', 'name': 'Thailand'}, {'code': 'TKL', 'name': 'Tokelau'}, {'code': 'TLS', 'name': 'Timor-Leste'}, {'code': 'TMP', 'name': 'East'}, {'code': 'TON', 'name': 'Tonga'}, {'code': 'TTO', 'name': 'Trinidad'}, {'code': 'TUN', 'name': 'Tunisia'}, {'code': 'TUR', 'name': 'Turkey'}, {'code': 'TUV', 'name': 'Tuvalu'}, {'code': 'TWN', 'name': 'Chinese'}, {'code': 'TZA', 'name': 'United'}, {'code': 'URY', 'name': 'Uruguay'}, {'code': 'USA', 'name': 'United'}, {'code': 'USSR', 'name': 'Former'}, {'code': 'USSR-ARM', 'name': 'Armenia'}, {'code': 'USSR-AZE', 'name': 'Azerbaidjan'}, {'code': 'USSR-BLR', 'name': 'Belarus'}, {'code': 'USSR-EST', 'name': 'Estonia'}, {'code': 'USSR-GEO', 'name': 'Georgia'}, {'code': 'USSR-KAZ', 'name': 'Kazakhstan'}, {'code': 'USSR-KGZ', 'name': 'Kirghizistan'}, {'code': 'USSR-LTU', 'name': 'Lithuania'}, {'code': 'USSR-LVA', 'name': 'Latvia'}, {'code': 'USSR-MDA', 'name': 'Moldova'}, {'code': 'USSR-RUS', 'name': 'Russia'}, {'code': 'USSR-TJK', 'name': 'Tadjikistan'}, {'code': 'USSR-TKM', 'name': 'Turkménistan'}, {'code': 'USSR-UKR', 'name': 'Ukraine'}, {'code': 'USSR-UZB', 'name': 'Uzbekistan'}, {'code': 'VAT', 'name': 'Holy'}, {'code': 'VCT', 'name': 'Saint'}, {'code': 'VEN', 'name': 'Venezuela'}, {'code': 'VGB', 'name': 'British'}, {'code': 'VIR', 'name': 'United'}, {'code': 'VNM', 'name': 'Vietnam'}, {'code': 'VUT', 'name': 'Vanuatu'}, {'code': 'WSM', 'name': 'Samoa'}, {'code': 'YEM', 'name': 'Yemen'}, {'code': 'ZAF', 'name': 'South'}, {'code': 'ZMB', 'name': 'Zambia'}, {'code': 'ZWE', 'name': 'Zimbabwe'}]

In [6]:
for country in list_of_country:
    mycursor.execute("INSERT INTO CountriesDatas_II.countries (code, name) VALUES (%s, %s)", (country['code'], country['name']))
mydb.commit()

print(mycursor.rowcount, "record inserted.")

1 record inserted.

In [7]:
#connect to the database
# cnx = mysql.connector.connect(user='username', password='password', host='hostname', database='CountriesDatas')

# cursor = cnx.cursor()

# #create the countries table
# cursor.execute("CREATE TABLE countries (code VARCHAR(255), name VARCHAR(255))")

#create the populations table
mycursor.execute("CREATE TABLE populations (id INT, LOCATION VARCHAR(255), TIME DATE, Value FLOAT)")

#close the cursor and connection
mycursor.close()
mydb.close()

In [20]:
populations_data = pd.read_csv('country.csv',index_col=False, delimiter = ',',encoding='UTF-8')
populations_data.head()
rows = populations_data.iloc[:,[0,5,6]]
rows.head()

rows = pd.DataFrame(rows,columns=['ID','LOCATION','TIME','Value'])
print(rows) 
for index, rows in populations_data.iterrows():
    query = '''INSERT INTO populations (ID,LOCATION,TIME,Value) VALUES (%s, %s, %s, %s) ON DUPLICATE KEY UPDATE LOCATION = VALUES(LOCATION), TIME = VALUES(TIME), Value = VALUES(Value)'''
    time_string = str(rows['TIME'])
    date_object = datetime.strptime(time_string, '%Y')
    mysql_date = date_object.strftime('%Y-%m-%d')
    values = (index, rows['LOCATION'], mysql_date,rows['Value'])
    mycursor.execute(query, values)

# commit the changes to the database
mydb.commit()

# close the cursor and connection
mycursor.close()
mydb.close()

       ID LOCATION  TIME          Value
0     NaN      AUS  1951       2.971132
1     NaN      AUS  1952       2.550554
2     NaN      AUS  1953       2.070283
3     NaN      AUS  1954       1.942078
4     NaN      AUS  1955       2.372448
...    ..      ...   ...            ...
16055 NaN     EU27  2017  228089.551500
16056 NaN     EU27  2018  228397.509500
16057 NaN     EU27  2019  228791.628000
16058 NaN     EU27  2020  228954.039500
16059 NaN     EU27  2021  228674.253500

[16060 rows x 4 columns]

In [24]:
mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="example",
    port="3307",
    database="CountriesDatas_II"
)
mycursor = mydb.cursor()
# check the connection
if mydb.is_connected():
    print("connected")
else:
    print("not connected")
    
# SELECT query with JOIN
query = '''SELECT populations.ID, countries.name, populations.TIME, populations.Value FROM populations JOIN countries ON populations.LOCATION = countries.code'''
mycursor.execute(query)

# fetch the results
results = mycursor.fetchall()

# print the results
for result in results:
    print(result)

# close the cursor and connection
mycursor.close()
mydb.close()

#Si cela ne résout pas le problème, vous pouvez également vérifier les informations de votre fichier de configuration de mysql (my.cnf) pour vous assurer qu'il n'y a pas de limite de connection.

connected
(0, 'Australia', datetime.date(1951, 1, 1), 2.97113)
(1, 'Australia', datetime.date(1952, 1, 1), 2.55055)
(2, 'Australia', datetime.date(1953, 1, 1), 2.07028)
(3, 'Australia', datetime.date(1954, 1, 1), 1.94208)
(4, 'Australia', datetime.date(1955, 1, 1), 2.37245)
(5, 'Australia', datetime.date(1956, 1, 1), 2.45443)
(6, 'Australia', datetime.date(1957, 1, 1), 2.27786)
(7, 'Australia', datetime.date(1958, 1, 1), 2.09747)
(8, 'Australia', datetime.date(1959, 1, 1), 2.17427)
(9, 'Australia', datetime.date(1960, 1, 1), 2.17374)
(10, 'Australia', datetime.date(1961, 1, 1), 2.26959)
(11, 'Australia', datetime.date(1962, 1, 1), 1.83)
(12, 'Australia', datetime.date(1963, 1, 1), 1.92888)
(13, 'Australia', datetime.date(1964, 1, 1), 1.96848)
(14, 'Australia', datetime.date(1965, 1, 1), 1.97184)
(15, 'Australia', datetime.date(1966, 1, 1), 2.28022)
(16, 'Australia', datetime.date(1967, 1, 1), 1.72059)
(17, 'Australia', datetime.date(1968, 1, 1), 1.77605)
(18, 'Australia', datetime.date(1969, 1, 1), 2.1183)
(19, 'Australia', datetime.date(1970, 1, 1), 1.99245)
(20, 'Australia', datetime.date(1971, 1, 1), 4.4767)
(21, 'Australia', datetime.date(1972, 1, 1), 1.80909)
(22, 'Australia', datetime.date(1973, 1, 1), 1.50991)
(23, 'Australia', datetime.date(1974, 1, 1), 1.61452)
(24, 'Australia', datetime.date(1975, 1, 1), 1.24192)
(25, 'Australia', datetime.date(1976, 1, 1), 1.00834)
(26, 'Australia', datetime.date(1977, 1, 1), 1.13411)
(27, 'Australia', datetime.date(1978, 1, 1), 1.17685)
(28, 'Australia', datetime.date(1979, 1, 1), 1.08971)
(29, 'Australia', datetime.date(1980, 1, 1), 1.23746)
(30, 'Australia', datetime.date(1981, 1, 1), 1.55086)
(31, 'Australia', datetime.date(1982, 1, 1), 1.74886)
(32, 'Australia', datetime.date(1983, 1, 1), 1.37791)
(33, 'Australia', datetime.date(1984, 1, 1), 1.20778)
(34, 'Australia', datetime.date(1985, 1, 1), 1.34101)
(35, 'Australia', datetime.date(1986, 1, 1), 1.45701)
(36, 'Australia', datetime.date(1987, 1, 1), 1.53277)
(37, 'Australia', datetime.date(1988, 1, 1), 1.64961)
(38, 'Australia', datetime.date(1989, 1, 1), 1.70729)
(39, 'Australia', datetime.date(1990, 1, 1), 1.49105)
(40, 'Australia', datetime.date(1991, 1, 1), 1.28278)
(41, 'Australia', datetime.date(1992, 1, 1), 1.12589)
(42, 'Australia', datetime.date(1993, 1, 1), 0.893508)
(43, 'Australia', datetime.date(1994, 1, 1), 0.967745)
(44, 'Australia', datetime.date(1995, 1, 1), 1.11996)
(45, 'Australia', datetime.date(1996, 1, 1), 1.22125)
(46, 'Australia', datetime.date(1997, 1, 1), 1.08792)
(47, 'Australia', datetime.date(1998, 1, 1), 1.00172)
(48, 'Australia', datetime.date(1999, 1, 1), 1.09998)
(49, 'Australia', datetime.date(2000, 1, 1), 1.15105)
(50, 'Australia', datetime.date(2001, 1, 1), 1.29225)
(51, 'Australia', datetime.date(2002, 1, 1), 1.14403)
(52, 'Australia', datetime.date(2003, 1, 1), 1.15683)
(53, 'Australia', datetime.date(2004, 1, 1), 1.07493)
(54, 'Australia', datetime.date(2005, 1, 1), 1.22473)
(55, 'Australia', datetime.date(2006, 1, 1), 1.3586)
(56, 'Australia', datetime.date(2007, 1, 1), 1.84175)
(57, 'Australia', datetime.date(2008, 1, 1), 2.02412)
(58, 'Australia', datetime.date(2009, 1, 1), 2.08222)
(59, 'Australia', datetime.date(2010, 1, 1), 1.56787)
(60, 'Australia', datetime.date(2011, 1, 1), 1.39923)
(61, 'Australia', datetime.date(2012, 1, 1), 1.76115)
(62, 'Australia', datetime.date(2013, 1, 1), 1.73605)
(63, 'Australia', datetime.date(2014, 1, 1), 1.50275)
(64, 'Australia', datetime.date(2015, 1, 1), 1.44962)
(65, 'Australia', datetime.date(2016, 1, 1), 1.5742)
(66, 'Australia', datetime.date(2017, 1, 1), 1.69879)
(67, 'Australia', datetime.date(2018, 1, 1), 1.54796)
(68, 'Australia', datetime.date(2019, 1, 1), 1.53329)
(69, 'Australia', datetime.date(2020, 1, 1), 1.2912)
(70, 'Australia', datetime.date(2021, 1, 1), 0.174657)
(71, 'Australia', datetime.date(1950, 1, 1), 4.1229)
(72, 'Australia', datetime.date(1951, 1, 1), 4.2537)
(73, 'Australia', datetime.date(1952, 1, 1), 4.3726)
(74, 'Australia', datetime.date(1953, 1, 1), 4.4626)
(75, 'Australia', datetime.date(1954, 1, 1), 4.5461)
(76, 'Australia', datetime.date(1955, 1, 1), 4.6563)
(77, 'Australia', datetime.date(1956, 1, 1), 4.776)
(78, 'Australia', datetime.date(1957, 1, 1), 4.8823)
(79, 'Australia', datetime.date(1958, 1, 1), 4.9766)
(80, 'Australia', datetime.date(1959, 1, 1), 5.0802)
(81, 'Australia', datetime.date(1960, 1, 1), 5.1923)
(82, 'Australia', datetime.date(1961, 1, 1), 5.3123)
(83, 'Australia', datetime.date(1962, 1, 1), 5.3992)
(84, 'Australia', datetime.date(1963, 1, 1), 5.4999)
(85, 'Australia', datetime.date(1964, 1, 1), 5.6052)
(86, 'Australia', datetime.date(1965, 1, 1), 5.7145)
(87, 'Australia', datetime.date(1966, 1, 1), 5.84159)
(88, 'Australia', datetime.date(1967, 1, 1), 5.93932)
(89, 'Australia', datetime.date(1968, 1, 1), 6.04323)
(90, 'Australia', datetime.date(1969, 1, 1), 6.17019)
(91, 'Australia', datetime.date(1970, 1, 1), 6.29198)
(92, 'Australia', datetime.date(1971, 1, 1), 6.56794)
(93, 'Australia', datetime.date(1972, 1, 1), 6.68515)
(94, 'Australia', datetime.date(1973, 1, 1), 6.78285)
(95, 'Australia', datetime.date(1974, 1, 1), 6.88967)
(96, 'Australia', datetime.date(1975, 1, 1), 6.96918)
(97, 'Australia', datetime.date(1976, 1, 1), 7.03203)
(98, 'Australia', datetime.date(1977, 1, 1), 7.1047)
(99, 'Australia', datetime.date(1978, 1, 1), 7.18129)
(100, 'Australia', datetime.date(1979, 1, 1), 7.25376)
(101, 'Australia', datetime.date(1980, 1, 1), 7.33806)
(102, 'Australia', datetime.date(1981, 1, 1), 7.44827)
(103, 'Australia', datetime.date(1982, 1, 1), 7.58091)
(104, 'Australia', datetime.date(1983, 1, 1), 7.68635)
(105, 'Australia', datetime.date(1984, 1, 1), 7.77821)
(106, 'Australia', datetime.date(1985, 1, 1), 7.88273)
(107, 'Australia', datetime.date(1986, 1, 1), 8.00019)
(108, 'Australia', datetime.date(1987, 1, 1), 8.11825)
(109, 'Australia', datetime.date(1988, 1, 1), 8.24895)
(110, 'Australia', datetime.date(1989, 1, 1), 8.38759)
(111, 'Australia', datetime.date(1990, 1, 1), 8.51127)
(112, 'Australia', datetime.date(1991, 1, 1), 8.61541)
(113, 'Australia', datetime.date(1992, 1, 1), 8.70826)
(114, 'Australia', datetime.date(1993, 1, 1), 8.78198)
(115, 'Australia', datetime.date(1994, 1, 1), 8.86368)
(116, 'Australia', datetime.date(1995, 1, 1), 8.96043)
(117, 'Australia', datetime.date(1996, 1, 1), 9.06532)
(118, 'Australia', datetime.date(1997, 1, 1), 9.15618)
(119, 'Australia', datetime.date(1998, 1, 1), 9.24314)
(120, 'Australia', datetime.date(1999, 1, 1), 9.34011)
(121, 'Australia', datetime.date(2000, 1, 1), 9.44347)
(122, 'Australia', datetime.date(2001, 1, 1), 9.56183)
(123, 'Australia', datetime.date(2002, 1, 1), 9.67548)
(124, 'Australia', datetime.date(2003, 1, 1), 9.7876)
(125, 'Australia', datetime.date(2004, 1, 1), 9.89595)
(126, 'Australia', datetime.date(2005, 1, 1), 10.0196)
(127, 'Australia', datetime.date(2006, 1, 1), 10.1594)
(128, 'Australia', datetime.date(2007, 1, 1), 10.3536)
(129, 'Australia', datetime.date(2008, 1, 1), 10.572)
(130, 'Australia', datetime.date(2009, 1, 1), 10.8008)
(131, 'Australia', datetime.date(2010, 1, 1), 10.9678)
(132, 'Australia', datetime.date(2011, 1, 1), 11.1182)
(133, 'Australia', datetime.date(2012, 1, 1), 11.313)
(134, 'Australia', datetime.date(2013, 1, 1), 11.5062)
(135, 'Australia', datetime.date(2014, 1, 1), 11.6679)
(136, 'Australia', datetime.date(2015, 1, 1), 11.8277)
(137, 'Australia', datetime.date(2016, 1, 1), 12.003)
(138, 'Australia', datetime.date(2017, 1, 1), 12.2038)
(139, 'Australia', datetime.date(2018, 1, 1), 12.391)
(140, 'Australia', datetime.date(2019, 1, 1), 12.5794)
(141, 'Australia', datetime.date(2020, 1, 1), 12.7329)
(142, 'Australia', datetime.date(2021, 1, 1), 12.7538)
(143, 'Australia', datetime.date(1950, 1, 1), 8.1787)
(144, 'Australia', datetime.date(1951, 1, 1), 8.4217)
(145, 'Australia', datetime.date(1952, 1, 1), 8.6365)
(146, 'Australia', datetime.date(1953, 1, 1), 8.8153)
(147, 'Australia', datetime.date(1954, 1, 1), 8.9865)
(148, 'Australia', datetime.date(1955, 1, 1), 9.1997)
(149, 'Australia', datetime.date(1956, 1, 1), 9.4255)
(150, 'Australia', datetime.date(1957, 1, 1), 9.6402)
(151, 'Australia', datetime.date(1958, 1, 1), 9.8424)
(152, 'Australia', datetime.date(1959, 1, 1), 10.0564)
(153, 'Australia', datetime.date(1960, 1, 1), 10.275)
(154, 'Australia', datetime.date(1961, 1, 1), 10.5082)
(155, 'Australia', datetime.date(1962, 1, 1), 10.7005)
(156, 'Australia', datetime.date(1963, 1, 1), 10.9069)
(157, 'Australia', datetime.date(1964, 1, 1), 11.1216)
(158, 'Australia', datetime.date(1965, 1, 1), 11.3409)
(159, 'Australia', datetime.date(1966, 1, 1), 11.5995)
(160, 'Australia', datetime.date(1967, 1, 1), 11.7991)
(161, 'Australia', datetime.date(1968, 1, 1), 12.0086)
(162, 'Australia', datetime.date(1969, 1, 1), 12.263)
(163, 'Australia', datetime.date(1970, 1, 1), 12.5073)
(164, 'Australia', datetime.date(1971, 1, 1), 13.0673)
(165, 'Australia', datetime.date(1972, 1, 1), 13.3037)
(166, 'Australia', datetime.date(1973, 1, 1), 13.5045)
(167, 'Australia', datetime.date(1974, 1, 1), 13.7226)
(168, 'Australia', datetime.date(1975, 1, 1), 13.893)
(169, 'Australia', datetime.date(1976, 1, 1), 14.0331)
(170, 'Australia', datetime.date(1977, 1, 1), 14.1922)
(171, 'Australia', datetime.date(1978, 1, 1), 14.3593)
(172, 'Australia', datetime.date(1979, 1, 1), 14.5157)
(173, 'Australia', datetime.date(1980, 1, 1), 14.6954)
(174, 'Australia', datetime.date(1981, 1, 1), 14.9233)
(175, 'Australia', datetime.date(1982, 1, 1), 15.1842)
(176, 'Australia', datetime.date(1983, 1, 1), 15.3935)
(177, 'Australia', datetime.date(1984, 1, 1), 15.5794)
(178, 'Australia', datetime.date(1985, 1, 1), 15.7883)
(179, 'Australia', datetime.date(1986, 1, 1), 16.0184)
(180, 'Australia', datetime.date(1987, 1, 1), 16.2639)
(181, 'Australia', datetime.date(1988, 1, 1), 16.5322)
(182, 'Australia', datetime.date(1989, 1, 1), 16.8144)
(183, 'Australia', datetime.date(1990, 1, 1), 17.0651)
(184, 'Australia', datetime.date(1991, 1, 1), 17.284)
(185, 'Australia', datetime.date(1992, 1, 1), 17.4786)
(186, 'Australia', datetime.date(1993, 1, 1), 17.6348)
(187, 'Australia', datetime.date(1994, 1, 1), 17.8055)
(188, 'Australia', datetime.date(1995, 1, 1), 18.0049)
(189, 'Australia', datetime.date(1996, 1, 1), 18.2248)
(190, 'Australia', datetime.date(1997, 1, 1), 18.423)
(191, 'Australia', datetime.date(1998, 1, 1), 18.6076)
(192, 'Australia', datetime.date(1999, 1, 1), 18.8123)
(193, 'Australia', datetime.date(2000, 1, 1), 19.0288)
(194, 'Australia', datetime.date(2001, 1, 1), 19.2747)
(195, 'Australia', datetime.date(2002, 1, 1), 19.4952)
(196, 'Australia', datetime.date(2003, 1, 1), 19.7207)
(197, 'Australia', datetime.date(2004, 1, 1), 19.9327)
(198, 'Australia', datetime.date(2005, 1, 1), 20.1768)
(199, 'Australia', datetime.date(2006, 1, 1), 20.451)
(200, 'Australia', datetime.date(2007, 1, 1), 20.8276)
(201, 'Australia', datetime.date(2008, 1, 1), 21.2492)
(202, 'Australia', datetime.date(2009, 1, 1), 21.6917)
(203, 'Australia', datetime.date(2010, 1, 1), 22.0317)
(204, 'Australia', datetime.date(2011, 1, 1), 22.34)
(205, 'Australia', datetime.date(2012, 1, 1), 22.7335)
(206, 'Australia', datetime.date(2013, 1, 1), 23.1281)
(207, 'Australia', datetime.date(2014, 1, 1), 23.4757)
(208, 'Australia', datetime.date(2015, 1, 1), 23.816)
(209, 'Australia', datetime.date(2016, 1, 1), 24.1909)
(210, 'Australia', datetime.date(2017, 1, 1), 24.6019)
(211, 'Australia', datetime.date(2018, 1, 1), 24.9827)
(212, 'Australia', datetime.date(2019, 1, 1), 25.3657)
(213, 'Australia', datetime.date(2020, 1, 1), 25.6933)
(214, 'Australia', datetime.date(2021, 1, 1), 25.7381)
(215, 'Australia', datetime.date(1950, 1, 1), 4055.8)
(216, 'Australia', datetime.date(1951, 1, 1), 4168.0)
(217, 'Australia', datetime.date(1952, 1, 1), 4263.9)
(218, 'Australia', datetime.date(1953, 1, 1), 4352.7)
(219, 'Australia', datetime.date(1954, 1, 1), 4440.4)
(220, 'Australia', datetime.date(1955, 1, 1), 4543.4)
(221, 'Australia', datetime.date(1956, 1, 1), 4649.5)
(222, 'Australia', datetime.date(1957, 1, 1), 4757.9)
(223, 'Australia', datetime.date(1958, 1, 1), 4865.8)
(224, 'Australia', datetime.date(1959, 1, 1), 4976.2)
(225, 'Australia', datetime.date(1960, 1, 1), 5082.7)
(226, 'Australia', datetime.date(1961, 1, 1), 5195.9)
(227, 'Australia', datetime.date(1962, 1, 1), 5301.3)
(228, 'Australia', datetime.date(1963, 1, 1), 5407.0)
(229, 'Australia', datetime.date(1964, 1, 1), 5516.4)
(230, 'Australia', datetime.date(1965, 1, 1), 5626.4)
(231, 'Australia', datetime.date(1966, 1, 1), 5757.91)
(232, 'Australia', datetime.date(1967, 1, 1), 5859.76)
(233, 'Australia', datetime.date(1968, 1, 1), 5965.4)
(234, 'Australia', datetime.date(1969, 1, 1), 6092.82)
(235, 'Australia', datetime.date(1970, 1, 1), 6215.37)
(236, 'Australia', datetime.date(1971, 1, 1), 6499.33)
(237, 'Australia', datetime.date(1972, 1, 1), 6618.51)
(238, 'Australia', datetime.date(1973, 1, 1), 6721.69)
(239, 'Australia', datetime.date(1974, 1, 1), 6832.9)
(240, 'Australia', datetime.date(1975, 1, 1), 6923.81)
(241, 'Australia', datetime.date(1976, 1, 1), 7001.05)
(242, 'Australia', datetime.date(1977, 1, 1), 7087.53)
(243, 'Australia', datetime.date(1978, 1, 1), 7177.96)
(244, 'Australia', datetime.date(1979, 1, 1), 7261.97)
(245, 'Australia', datetime.date(1980, 1, 1), 7357.3)
(246, 'Australia', datetime.date(1981, 1, 1), 7474.99)
(247, 'Australia', datetime.date(1982, 1, 1), 7603.33)
(248, 'Australia', datetime.date(1983, 1, 1), 7707.13)
(249, 'Australia', datetime.date(1984, 1, 1), 7801.18)
(250, 'Australia', datetime.date(1985, 1, 1), 7905.58)
(251, 'Australia', datetime.date(1986, 1, 1), 8018.16)
(252, 'Australia', datetime.date(1987, 1, 1), 8145.62)
(253, 'Australia', datetime.date(1988, 1, 1), 8283.22)
(254, 'Australia', datetime.date(1989, 1, 1), 8426.83)
(255, 'Australia', datetime.date(1990, 1, 1), 8553.86)
(256, 'Australia', datetime.date(1991, 1, 1), 8668.63)
(257, 'Australia', datetime.date(1992, 1, 1), 8770.38)
(258, 'Australia', datetime.date(1993, 1, 1), 8852.83)
(259, 'Australia', datetime.date(1994, 1, 1), 8941.79)
(260, 'Australia', datetime.date(1995, 1, 1), 9044.45)
(261, 'Australia', datetime.date(1996, 1, 1), 9159.44)
(262, 'Australia', datetime.date(1997, 1, 1), 9266.86)
(263, 'Australia', datetime.date(1998, 1, 1), 9364.44)
(264, 'Australia', datetime.date(1999, 1, 1), 9472.16)
(265, 'Australia', datetime.date(2000, 1, 1), 9585.34)
(266, 'Australia', datetime.date(2001, 1, 1), 9712.88)
(267, 'Australia', datetime.date(2002, 1, 1), 9819.73)
(268, 'Australia', datetime.date(2003, 1, 1), 9933.14)
(269, 'Australia', datetime.date(2004, 1, 1), 10036.8)
(270, 'Australia', datetime.date(2005, 1, 1), 10157.2)
(271, 'Australia', datetime.date(2006, 1, 1), 10291.5)
(272, 'Australia', datetime.date(2007, 1, 1), 10474.0)
(273, 'Australia', datetime.date(2008, 1, 1), 10677.2)
(274, 'Australia', datetime.date(2009, 1, 1), 10890.9)
(275, 'Australia', datetime.date(2010, 1, 1), 11063.9)
(276, 'Australia', datetime.date(2011, 1, 1), 11221.8)
(277, 'Australia', datetime.date(2012, 1, 1), 11420.5)
(278, 'Australia', datetime.date(2013, 1, 1), 11622.0)
(279, 'Australia', datetime.date(2014, 1, 1), 11807.8)
(280, 'Australia', datetime.date(2015, 1, 1), 11988.3)
(281, 'Australia', datetime.date(2016, 1, 1), 12187.9)
(282, 'Australia', datetime.date(2017, 1, 1), 12398.1)
(283, 'Australia', datetime.date(2018, 1, 1), 12591.6)
(284, 'Australia', datetime.date(2019, 1, 1), 12786.4)
(285, 'Australia', datetime.date(2020, 1, 1), 12960.3)
(286, 'Australia', datetime.date(2021, 1, 1), 12984.3)
(287, 'Austria', datetime.date(1951, 1, 1), 0.00506121)
(288, 'Austria', datetime.date(1952, 1, 1), -0.110721)
(289, 'Austria', datetime.date(1953, 1, 1), 0.0680017)
(290, 'Austria', datetime.date(1954, 1, 1), 0.111446)
(291, 'Austria', datetime.date(1955, 1, 1), 0.0961931)
(292, 'Austria', datetime.date(1956, 1, 1), 0.0787979)
(293, 'Austria', datetime.date(1957, 1, 1), 0.194193)
(294, 'Austria', datetime.date(1958, 1, 1), 0.308619)
(295, 'Austria', datetime.date(1959, 1, 1), 0.386026)
(296, 'Austria', datetime.date(1960, 1, 1), 0.473431)
(297, 'Austria', datetime.date(1961, 1, 1), 0.549979)
(298, 'Austria', datetime.date(1962, 1, 1), 0.614778)
(299, 'Austria', datetime.date(1963, 1, 1), 0.64443)
(300, 'Austria', datetime.date(1964, 1, 1), 0.668775)
(301, 'Austria', datetime.date(1965, 1, 1), 0.651845)
(302, 'Austria', datetime.date(1966, 1, 1), 0.703862)
(303, 'Austria', datetime.date(1967, 1, 1), 0.750225)
(304, 'Austria', datetime.date(1968, 1, 1), 0.520605)
(305, 'Austria', datetime.date(1969, 1, 1), 0.345929)
(306, 'Austria', datetime.date(1970, 1, 1), 0.349829)
(307, 'Austria', datetime.date(1971, 1, 1), 0.447243)
(308, 'Austria', datetime.date(1972, 1, 1), 0.582883)
(309, 'Austria', datetime.date(1973, 1, 1), 0.555579)
(310, 'Austria', datetime.date(1974, 1, 1), 0.170351)
(311, 'Austria', datetime.date(1975, 1, 1), -0.264968)
(312, 'Austria', datetime.date(1976, 1, 1), -0.176516)
(313, 'Austria', datetime.date(1977, 1, 1), 0.0383979)
(314, 'Austria', datetime.date(1978, 1, 1), -0.0809283)
(315, 'Austria', datetime.date(1979, 1, 1), -0.170318)
(316, 'Austria', datetime.date(1980, 1, 1), 0.000105968)
(317, 'Austria', datetime.date(1981, 1, 1), 0.255344)
(318, 'Austria', datetime.date(1982, 1, 1), 0.0717427)
(319, 'Austria', datetime.date(1983, 1, 1), -0.16147)
(320, 'Austria', datetime.date(1984, 1, 1), -0.00629471)
(321, 'Austria', datetime.date(1985, 1, 1), 0.0469488)
(322, 'Austria', datetime.date(1986, 1, 1), 0.0635824)
(323, 'Austria', datetime.date(1987, 1, 1), 0.0633042)
(324, 'Austria', datetime.date(1988, 1, 1), 0.141671)
(325, 'Austria', datetime.date(1989, 1, 1), 0.451517)
(326, 'Austria', datetime.date(1990, 1, 1), 0.764925)
(327, 'Austria', datetime.date(1991, 1, 1), 1.00342)
(328, 'Austria', datetime.date(1992, 1, 1), 1.10663)
(329, 'Austria', datetime.date(1993, 1, 1), 0.828025)
(330, 'Austria', datetime.date(1994, 1, 1), 0.385624)
(331, 'Austria', datetime.date(1995, 1, 1), 0.153224)
(332, 'Austria', datetime.date(1996, 1, 1), 0.135098)
(333, 'Austria', datetime.date(1997, 1, 1), 0.113393)
(334, 'Austria', datetime.date(1998, 1, 1), 0.109789)
(335, 'Austria', datetime.date(1999, 1, 1), 0.19474)
(336, 'Austria', datetime.date(2000, 1, 1), 0.240769)
(337, 'Austria', datetime.date(2001, 1, 1), 0.383533)
(338, 'Austria', datetime.date(2002, 1, 1), 0.495232)
(339, 'Austria', datetime.date(2003, 1, 1), 0.446962)
(340, 'Austria', datetime.date(2004, 1, 1), 0.630629)
(341, 'Austria', datetime.date(2005, 1, 1), 0.683486)
(342, 'Austria', datetime.date(2006, 1, 1), 0.518767)
(343, 'Austria', datetime.date(2007, 1, 1), 0.329477)
(344, 'Austria', datetime.date(2008, 1, 1), 0.317678)
(345, 'Austria', datetime.date(2009, 1, 1), 0.239643)
(346, 'Austria', datetime.date(2010, 1, 1), 0.234802)
(347, 'Austria', datetime.date(2011, 1, 1), 0.328487)
(348, 'Austria', datetime.date(2012, 1, 1), 0.450341)
(349, 'Austria', datetime.date(2013, 1, 1), 0.604286)
(350, 'Austria', datetime.date(2014, 1, 1), 0.786837)
(351, 'Austria', datetime.date(2015, 1, 1), 1.00173)
(352, 'Austria', datetime.date(2016, 1, 1), 1.27802)
(353, 'Austria', datetime.date(2017, 1, 1), 0.63236)
(354, 'Austria', datetime.date(2018, 1, 1), 0.484749)
(355, 'Austria', datetime.date(2019, 1, 1), 0.451814)
(356, 'Austria', datetime.date(2020, 1, 1), 0.441649)
(357, 'Austria', datetime.date(2021, 1, 1), 0.388871)
(358, 'Austria', datetime.date(1950, 1, 1), 3.21782)
(359, 'Austria', datetime.date(1951, 1, 1), 3.2176)
(360, 'Austria', datetime.date(1952, 1, 1), 3.21473)
(361, 'Austria', datetime.date(1953, 1, 1), 3.21833)
(362, 'Austria', datetime.date(1954, 1, 1), 3.22335)
(363, 'Austria', datetime.date(1955, 1, 1), 3.22769)
(364, 'Austria', datetime.date(1956, 1, 1), 3.2313)
(365, 'Austria', datetime.date(1957, 1, 1), 3.23899)
(366, 'Austria', datetime.date(1958, 1, 1), 3.2506)
(367, 'Austria', datetime.date(1959, 1, 1), 3.26494)

In [25]:
# convert results to dataframe
df = pd.DataFrame(results, columns = ['ID', 'name', 'date', 'Value'])

# print the dataframe
print(df)

          ID       name        date     Value
0          0  Australia  1951-01-01  2.971130
1          1  Australia  1952-01-01  2.550550
2          2  Australia  1953-01-01  2.070280
3          3  Australia  1954-01-01  1.942080
4          4  Australia  1955-01-01  2.372450
...      ...        ...         ...       ...
12332  15627  Singapore  2016-01-01  0.790967
12333  15628  Singapore  2017-01-01  0.819538
12334  15629  Singapore  2018-01-01  0.718317
12335  15630  Singapore  2019-01-01  0.799292
12336  15631  Singapore  2020-01-01  0.447096

[12337 rows x 4 columns]